// <auto-generated />
using System;
using RepositoryPattern.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RepositoryPattern.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("RepositoryPattern.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Laptop",
                            Price = 750.0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Mouse",
                            Price = 25.5
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Keyboard",
                            Price = 45.0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Monitor",
                            Price = 180.0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Headphones",
                            Price = 60.0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Webcam",
                            Price = 70.0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Microphone",
                            Price = 95.0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Printer",
                            Price = 150.0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Tablet",
                            Price = 300.0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Smartphone",
                            Price = 650.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Smartphone",
                            Price = 600.0
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Smartphone",
                            Price = 550.0
                        });
                });

            modelBuilder.Entity("RepositoryPattern.Model.ProductReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reviewer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Reviewer = "Ahmad",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Reviewer = "Sara",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Reviewer = "Ali",
                            Stars = 3
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Reviewer = "Lina",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            ProductId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Reviewer = "Omar",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            ProductId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Reviewer = "Noor",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            ProductId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Reviewer = "Huda",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            ProductId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Reviewer = "Yousef",
                            Stars = 3
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Reviewer = "Rana",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000010"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Reviewer = "Khaled",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            ProductId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Reviewer = "Zaid",
                            Stars = 3
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000012"),
                            ProductId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Reviewer = "Maya",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000013"),
                            ProductId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Reviewer = "Fadi",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000014"),
                            ProductId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Reviewer = "Dana",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000015"),
                            ProductId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Reviewer = "Sami",
                            Stars = 3
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000016"),
                            ProductId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Reviewer = "Reem",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000017"),
                            ProductId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Reviewer = "Tariq",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000018"),
                            ProductId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Reviewer = "Salma",
                            Stars = 5
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000019"),
                            ProductId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Reviewer = "Nader",
                            Stars = 4
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000020"),
                            ProductId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Reviewer = "Farah",
                            Stars = 5
                        });
                });

            modelBuilder.Entity("RepositoryPattern.Model.ProductReview", b =>
                {
                    b.HasOne("RepositoryPattern.Model.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RepositoryPattern.Model.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
