# For more info on HTTP files go to https://aka.ms/vs/httpfile

@baseURL = https://localhost:7261

###
GET {{baseURL}}/hamzeh.com-controller-0/22?id=55

###
GET {{baseURL}}/hamzeh.com-controller-1/22?id=55
###
GET {{baseURL}}/hamzeh.com-controller-2/22?id=55
