# For more info on HTTP files go to https://aka.ms/vs/httpfile

@baseURL = https://localhost:7012

###
GET {{baseURL}}/api/products/1?isInclude=true
###
GET {{baseURL}}/api/products/1?isInclude=false
api-version:1.0
###
GET {{baseURL}}/api/products/1?isInclude=false
api-version:2.0