# For more info on HTTP files go to https://aka.ms/vs/httpfile


@baseURL = https://localhost:7141

### GetValueByKey
GET {{baseURL}}/get-value-by-key

### GetValueByPath
GET {{baseURL}}/get-value-by-path

### GetValueByConnectionString
GET {{baseURL}}/get-value-by-connection-string

### GetValueByGetValueMethod
GET {{baseURL}}/get-value-by-get-value

### GetValueByGetSectionMethodReturnObject
GET {{baseURL}}/get-object

### GetValueByGetSectionMethodReturnObjectAsBind
GET {{baseURL}}/get-object-bind


